# Generated by Django 6.0.3 on 2026-03-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_options_alter_service_duration_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='duration',
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название услуги'),
        ),
    ]
