# Generated by Django 6.0.3 on 2026-03-19 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_employee_options_alter_employee_login_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='login',
            field=models.CharField(max_length=50, unique=True, verbose_name='Логин'),
        ),
    ]
